# Exemplo montando a partir das explicações da página da imagem e de um tutorial
# https://hub.docker.com/_/postgres
# https://geshan.com.np/blog/2021/12/docker-postgres/
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  database:
    driver: local